.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma 1  "oma 0.17.1" 
.SH NAME
oma
.SH SYNOPSIS
\fBoma\fR [\fB\-d\fR|\fB\-\-dry\-run\fR] [\fB\-\-debug\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-dry\-run\fR
Dry\-run oma
.TP
\fB\-\-debug\fR
Debug mode (for \-\-dry\-run argument
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
oma\-install(1)
Install Package
.TP
oma\-upgrade(1)
Update Package
.TP
oma\-download(1)
Download Package
.TP
oma\-remove(1)
Delete Package
.TP
oma\-refresh(1)
efresh Package database
.TP
oma\-show(1)
Show package
.TP
oma\-search(1)
Search Packages
.TP
oma\-list\-files(1)
Query package list files
.TP
oma\-provides(1)
Search file from packages
.TP
oma\-fix\-broken(1)
Fix system dependencies broken status
.TP
oma\-pick(1)
Pick a package version
.TP
oma\-mark(1)
Mark a package status
.TP
oma\-list(1)
List of packages
.TP
oma\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.17.1
