.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-remove 1  "remove " 
.SH NAME
remove \- Remove package(s)
.SH SYNOPSIS
\fBremove\fR [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-f\fR|\fB\-\-fix\-broken\fR] [\fB\-\-fix\-dpkg\-status\fR] [\fB\-\-force\-unsafe\-io\fR] [\fB\-\-force\-yes\fR] [\fB\-\-force\-confnew\fR] [\fB\-\-no\-autoremove\fR] [\fB\-\-remove\-config\fR] [\fB\-\-no\-clean\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPACKAGES\fR] 
.SH DESCRIPTION
Remove package(s)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH ARGUMENT
.TP
[\fIPACKAGES\fR]
Package(s) to remove
.SH OPTIONS
.TP
\fB\-y\fR, \fB\-\-yes\fR
Bypass confirmation prompts
.TP
\fB\-f\fR, \fB\-\-fix\-broken\fR
Resolve broken dependency(ies) in the system
.TP
\fB\-\-fix\-dpkg\-status\fR
Fix "broken" dpkg status
.TP
\fB\-\-force\-unsafe\-io\fR
Perform package changes without fsync(2) (no periodic data sync to the storage device, DANGEROUS but fast)
.TP
\fB\-\-force\-yes\fR
Ignore repository and package dependency issue(s)
.TP
\fB\-\-force\-confnew\fR
Replace configuration file(s) in the system those shipped in the package(s) to be installed (equivalent to `dpkg \-\-force\-confnew`)
.TP
\fB\-\-no\-autoremove\fR
Do not automatically remove unneeded package(s)
.TP
\fB\-\-remove\-config\fR
Remove configuration file(s) during package removal (like `apt purge\*(Aq)
.TP
\fB\-\-no\-clean\fR
Do not clean local package cache
