.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-clean 1  "clean " 
.SH NAME
clean \- Clear local package cache
.SH SYNOPSIS
\fBclean\fR [\fB\-\-keep\-downloadable\fR] [\fB\-\-keep\-downloadable\-and\-installed\fR] [\fB\-\-keep\-installed\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Clear local package cache
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH OPTIONS
.TP
\fB\-\-keep\-downloadable\fR
Keep downloadable packages
.TP
\fB\-\-keep\-downloadable\-and\-installed\fR
Keep downloadable and installed packages
.TP
\fB\-\-keep\-installed\fR
Keep installed packages
