.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-history 1  "history " 
.SH NAME
history \- Show a history/log of package changes in the system
.SH SYNOPSIS
\fBhistory\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show a history/log of package changes in the system
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
