.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-refresh 1  "refresh " 
.SH NAME
refresh \- Refresh repository metadata/catalog
.SH SYNOPSIS
\fBrefresh\fR [\fB\-\-no\-refresh\-topics\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Refresh repository metadata/catalog
.SH OPTIONS
.TP
\fB\-\-no\-refresh\-topics\fR
Do not refresh topics manifest.json file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
