.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-fix-broken 1  "fix-broken " 
.SH NAME
fix\-broken \- Resolve broken system dependencies in the system
.SH SYNOPSIS
\fBfix\-broken\fR [\fB\-n\fR|\fB\-\-no\-fix\-dpkg\-status\fR] [\fB\-\-force\-unsafe\-io\fR] [\fB\-\-force\-yes\fR] [\fB\-\-force\-confnew\fR] [\fB\-\-autoremove\fR] [\fB\-\-remove\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Resolve broken system dependencies in the system
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-no\-fix\-dpkg\-status\fR
Do not fix dpkg broken status
.TP
\fB\-\-force\-unsafe\-io\fR
Install package(s) without fsync(2)
.TP
\fB\-\-force\-yes\fR
Ignore repository and package dependency issues
.TP
\fB\-\-force\-confnew\fR
Replace configuration file(s) in the system those shipped in the package(s) to be installed (invokes `dpkg \-\-force\-confnew`)
.TP
\fB\-\-autoremove\fR
Auto remove unnecessary package(s)
.TP
\fB\-\-remove\-config\fR
Remove package(s) also remove configuration file(s), like apt purge
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
