.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-upgrade 1  "upgrade " 
.SH NAME
upgrade \- Upgrade packages installed on the system
.SH SYNOPSIS
\fBupgrade\fR [\fB\-n\fR|\fB\-\-no\-fixbroken\fR] [\fB\-n\fR|\fB\-\-no\-fix\-dpkg\-status\fR] [\fB\-\-force\-unsafe\-io\fR] [\fB\-\-no\-refresh\fR] [\fB\-\-force\-yes\fR] [\fB\-\-force\-confnew\fR] [\fB\-\-no\-refresh\-topics\fR] [\fB\-\-autoremove\fR] [\fB\-\-remove\-config\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPACKAGES\fR] 
.SH DESCRIPTION
Upgrade packages installed on the system
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-no\-fixbroken\fR
Do not fix apt broken status
.TP
\fB\-n\fR, \fB\-\-no\-fix\-dpkg\-status\fR
Do not fix dpkg broken status
.TP
\fB\-\-force\-unsafe\-io\fR
Install package(s) without fsync(2)
.TP
\fB\-\-no\-refresh\fR
Do not refresh repository metadata
.TP
\fB\-\-force\-yes\fR
Ignore repository and package dependency issues
.TP
\fB\-\-force\-confnew\fR
Replace configuration file(s) in the system those shipped in the package(s) to be installed (invokes `dpkg \-\-force\-confnew`)
.TP
\fB\-\-no\-refresh\-topics\fR
Do not refresh topics manifest.json file
.TP
\fB\-\-autoremove\fR
Auto remove unnecessary package(s)
.TP
\fB\-\-remove\-config\fR
Remove package(s) also remove configuration file(s), like apt purge
.TP
\fB\-y\fR, \fB\-\-yes\fR
Bypass confirmation prompts
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPACKAGES\fR]
Package(s) to install
