.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-install 1  "install " 
.SH NAME
install \- Install package(s) from the repository
.SH SYNOPSIS
\fBinstall\fR [\fB\-\-install\-recommends\fR] [\fB\-\-reinstall\fR] [\fB\-\-install\-suggests\fR] [\fB\-\-no\-install\-recommends\fR] [\fB\-\-no\-install\-suggests\fR] [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-install\-dbg\fR] [\fB\-f\fR|\fB\-\-fix\-broken\fR] [\fB\-n\fR|\fB\-\-no\-fix\-dpkg\-status\fR] [\fB\-\-force\-unsafe\-io\fR] [\fB\-\-no\-refresh\fR] [\fB\-\-force\-yes\fR] [\fB\-\-force\-confnew\fR] [\fB\-\-no\-refresh\-topics\fR] [\fB\-\-autoremove\fR] [\fB\-\-remove\-config\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPACKAGES\fR] 
.SH DESCRIPTION
Install package(s) from the repository
.SH OPTIONS
.TP
\fB\-\-install\-recommends\fR
Install recommended package(s)
.TP
\fB\-\-reinstall\fR
Reinstall package(s)
.TP
\fB\-\-install\-suggests\fR
Install suggested package(s)
.TP
\fB\-\-no\-install\-recommends\fR
Do not install recommended package(s)
.TP
\fB\-\-no\-install\-suggests\fR
Do not install suggested package(s)
.TP
\fB\-y\fR, \fB\-\-yes\fR
Bypass confirmation prompts
.TP
\fB\-\-install\-dbg\fR
Install debug symbol package
.TP
\fB\-f\fR, \fB\-\-fix\-broken\fR
Fix apt resolver broken status
.TP
\fB\-n\fR, \fB\-\-no\-fix\-dpkg\-status\fR
Do not fix dpkg broken status
.TP
\fB\-\-force\-unsafe\-io\fR
Install package(s) without fsync(2)
.TP
\fB\-\-no\-refresh\fR
Do not refresh repository metadata
.TP
\fB\-\-force\-yes\fR
Ignore repository and package dependency issues
.TP
\fB\-\-force\-confnew\fR
Replace configuration file(s) in the system those shipped in the package(s) to be installed (invokes `dpkg \-\-force\-confnew`)
.TP
\fB\-\-no\-refresh\-topics\fR
Do not refresh topics manifest.json file
.TP
\fB\-\-autoremove\fR
Auto remove unnecessary package(s)
.TP
\fB\-\-remove\-config\fR
Remove package(s) also remove configuration file(s), like apt purge
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPACKAGES\fR]
Package(s) to install
