.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-download 1  "download " 
.SH NAME
download \- Download package(s) from the repository
.SH SYNOPSIS
\fBdownload\fR [\fB\-p\fR|\fB\-\-path\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGES\fR> 
.SH DESCRIPTION
Download package(s) from the repository
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-path\fR=\fIPATH\fR [default: .]
The path where package(s) should be downloaded to
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGES\fR>
Package(s) to download
