.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-depends 1  "depends " 
.SH NAME
depends \- 查詢指定軟體套件的依賴關係
.SH SYNOPSIS
\fBdepends\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGES\fR> 
.SH DESCRIPTION
查詢指定軟體套件的依賴關係
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH 參數
.TP
<\fIPACKAGES\fR>
要查詢依賴關係的軟體套件
.SH 選項
.TP
\fB\-\-json\fR
設定輸出格式為 JSON
