.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-mark 1  "mark " 
.SH NAME
mark \- 標記指定軟體套件的狀態
.SH SYNOPSIS
\fBmark\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIACTION\fR> <\fIPACKAGES\fR> 
.SH DESCRIPTION
標記指定軟體套件的狀態
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH 參數
.TP
<\fIACTION\fR>
標記指定軟體套件的狀態，oma 將在完成標記後重新計算依賴關係
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
hold: 鎖定軟體套件版本，這會防止指定軟體套件被更新或降級
.IP \(bu 2
unhold: 解除鎖定軟體套件版本，這會取消指定軟體套件的「保留」狀態
.IP \(bu 2
manual: 將軟體套件標記為手動安裝，這會防止指定軟體套件在所有逆向依賴關係被移除後被移除
.IP \(bu 2
auto: 將軟體套件標記為自動安裝，這會標記指定軟體套件在所有逆向依賴關係被移除後被移除
.RE
.TP
<\fIPACKAGES\fR>
要標記狀態的軟體套件
