.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-remove 1  "remove " 
.SH NAME
remove \- 移除軟體套件
.SH SYNOPSIS
\fBremove\fR [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-f\fR|\fB\-\-fix\-broken\fR] [\fB\-\-fix\-dpkg\-status\fR] [\fB\-\-force\-unsafe\-io\fR] [\fB\-\-force\-yes\fR] [\fB\-\-force\-confnew\fR] [\fB\-\-no\-autoremove\fR] [\fB\-\-remove\-config\fR] [\fB\-\-no\-clean\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPACKAGES\fR] 
.SH DESCRIPTION
移除軟體套件
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH 參數
.TP
[\fIPACKAGES\fR]
要移除的軟體套件
.SH 選項
.TP
\fB\-y\fR, \fB\-\-yes\fR
跳過確認提示
.TP
\fB\-f\fR, \fB\-\-fix\-broken\fR
解決系統中的依賴問題
.TP
\fB\-\-fix\-dpkg\-status\fR
Fix "broken" dpkg status
.TP
\fB\-\-force\-unsafe\-io\fR
執行軟體套件變更時不啟用 fsync(2)（資料不會及時同步到存儲設備，非常危險但操作更快）
.TP
\fB\-\-force\-yes\fR
略過軟體庫和軟體套件依賴問題
.TP
\fB\-\-force\-confnew\fR
使用軟體套件中附帶的設定檔替換系統中的設定檔（等效於 `dpkg \-\-force\-confnew`）
.TP
\fB\-\-no\-autoremove\fR
不要自動移除不再需要的軟體套件
.TP
\fB\-\-remove\-config\fR
在移除軟體套件時同時清理設定檔（類似 `apt purge\*(Aq）
.TP
\fB\-\-no\-clean\fR
Do not clean local package cache
