.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-clean 1  "clean " 
.SH NAME
clean \- 清理本機軟體套件快取
.SH SYNOPSIS
\fBclean\fR [\fB\-\-keep\-downloadable\fR] [\fB\-\-keep\-downloadable\-and\-installed\fR] [\fB\-\-keep\-installed\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
清理本機軟體套件快取
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH 選項
.TP
\fB\-\-keep\-downloadable\fR
保留仍能夠下載的軟體套件
.TP
\fB\-\-keep\-downloadable\-and\-installed\fR
保留仍能夠下載及已安裝的軟體套件
.TP
\fB\-\-keep\-installed\fR
保留已安裝的軟體套件
