.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma-show 1  "show " 
.SH NAME
show \- 顯示指定軟體套件的資訊
.SH SYNOPSIS
\fBshow\fR [\fB\-a\fR|\fB\-\-all\fR] [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGES\fR> 
.SH DESCRIPTION
顯示指定軟體套件的資訊
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH 參數
.TP
<\fIPACKAGES\fR>
要顯示的軟體套件
.SH 選項
.TP
\fB\-a\fR, \fB\-\-all\fR
顯示指定軟體套件的所有版本的資訊
.TP
\fB\-\-json\fR
設定輸出格式為 JSON
