.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH oma 1  "oma 1.27.0-dev" 
.SH NAME
oma \- 易用、防呆的 APT 軟體套件管理器
.SH SYNOPSIS
\fBoma\fR [\fB\-\-dry\-run\fR] [\fB\-\-debug\fR] [\fB\-\-color\fR] [\fB\-\-follow\-terminal\-color\fR] [\fB\-\-no\-progress\fR] [\fB\-\-no\-check\-dbus\fR] [\fB\-\-no\-check\-battery\fR] [\fB\-\-no\-take\-wake\-lock\fR] [\fB\-v\fR|\fB\-\-version\fR] [\fB\-\-sysroot\fR] [\fB\-o\fR|\fB\-\-apt\-options\fR] [\fB\-\-no\-bell\fR] [\fB\-t\fR|\fB\-\-download\-threads\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-\-no\-config\fR] [\fB\-\-user\-agent\fR] [\fI指令\fR]
.SH DESCRIPTION
易用、防呆的 APT 軟體套件管理器
.SH 選項
.TP
\fB\-\-dry\-run\fR
使用「試運行 (dry\-run)」模式執行 oma。該模式可用於推演操作相對應的變更，而無須實際對系統進行變更，便於測試。
.TP
\fB\-\-debug\fR
執行 oma 時啟用包含程式參數及執行資料的除錯輸出，以便讓開發者及系統管理者調查並回報問題。
.TP
\fB\-\-color\fR \fI<COLOR>\fR [default: auto]
指定 oma 的顏色輸出模式
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
auto
.IP \(bu 2
always
.IP \(bu 2
never
.RE
.TP
\fB\-\-follow\-terminal\-color\fR
使彩色輸出跟隨終端配色
.TP
\fB\-\-no\-progress\fR
不要顯示進度列
.TP
\fB\-\-no\-check\-dbus\fR
不要檢查 D\-Bus 可用性
.TP
\fB\-\-no\-check\-battery\fR
不要檢查電源狀態（即系統是否正在使用電池供電）
.TP
\fB\-\-no\-take\-wake\-lock\fR
不要佔用工作階段喚醒鎖（即不要禁用電源管理）
.TP
\fB\-v\fR, \fB\-\-version\fR
顯示版本號
.TP
\fB\-\-sysroot\fR \fI<SYSROOT>\fR [default: /]
指定目標作業系統的根路徑
.TP
\fB\-o\fR, \fB\-\-apt\-options\fR \fI<APT_OPTIONS>\fR
指定 APT 選項
.TP
\fB\-\-no\-bell\fR
在 oma 完成操作後不要發送終端提示音
.TP
\fB\-t\fR, \fB\-\-download\-threads\fR \fI<DOWNLOAD_THREADS>\fR
設定平行下載的執行緒數量（預設為 4）
.TP
\fB\-h\fR, \fB\-\-help\fR
顯示幫助資訊
.TP
\fB\-\-no\-config\fR
不使用設定檔，使用預設設定
.TP
\fB\-\-user\-agent\fR \fI<USER_AGENT>\fR
指定用於 HTTP 請求的 User\-Agent 標頭字串
.SH 指令
.TP
oma\-install(1)
從軟體庫中安裝軟體套件
.TP
oma\-upgrade(1)
升級系統中安裝的軟體套件
.TP
oma\-download(1)
從軟體庫下載軟體套件
.TP
oma\-remove(1)
移除軟體套件
.TP
oma\-refresh(1)
重新整理軟體庫後設資料
.TP
oma\-show(1)
顯示指定軟體套件的資訊
.TP
oma\-search(1)
搜尋軟體庫中可用的軟體套件
.TP
oma\-files(1)
列出指定軟體套件中的檔案
.TP
oma\-provides(1)
搜尋提供指定路徑/檔案的軟體套件
.TP
oma\-fix\-broken(1)
解決系統中被破壞的依賴關係
.TP
oma\-pick(1)
選擇並安裝軟體套件的指定版本
.TP
oma\-mark(1)
標記指定軟體套件的狀態
.TP
oma\-list(1)
列出可用的軟體套件
.TP
oma\-depends(1)
查詢指定軟體套件的依賴關係
.TP
oma\-rdepends(1)
查詢指定軟體套件的逆向依賴關係
.TP
oma\-clean(1)
清理本機軟體套件快取
.TP
oma\-history(1)
顯示系統軟體套件變更歷史
.TP
oma\-undo(1)
取消系統軟體套件變更
.TP
oma\-tui(1)
互動式終端使用者介面
.TP
oma\-version(1)
顯示版本號
.TP
oma\-size\-analyzer(1)
分析軟體套件磁碟佔用
.TP
oma\-tree(1)
顯示指定軟體套件的依賴樹
.TP
oma\-why(1)
透過樹形視覺化呈現指定軟體套件被安裝的原因
.SH EXTRA
本 oma 具有超级小熊猫力！
.SH VERSION
v1.27.0\-dev
