pub mod clean;
pub mod command_not_found;
pub mod contents_find;
pub mod depends;
pub mod download;
pub mod fix_broken;
pub mod history;
pub mod install;
pub mod list;
pub mod mark;
#[cfg(feature = "aosc")]
pub mod mirror;
pub mod pick;
pub mod pkgnames;
pub mod rdepends;
pub mod refresh;
pub mod remove;
pub mod search;
pub mod show;
#[cfg(feature = "aosc")]
pub mod topics;
pub mod upgrade;
pub mod utils;
pub mod generate;
