APT {
  Install-Recommends "true";
  Install-Suggests "false";
  Build-Essential "build-essential";
};

Dir::State "var/lib/apt";
Dir::Cache "var/cache/apt";
Dir::Etc "etc/apt";

Acquire::IndexTargets {
  deb::Packages {
    MetaKey "$(COMPONENT)/binary-$(ARCHITECTURE)/Packages";
  };
};

# This is a comment
#include "/etc/apt/extra.conf"
#clear Dir::Cache
